### ISSUE TITLE
Add Docker Compose support with persistent SQLite volume

### ISSUE THREAD

**Issue by nanotaboada** [nanotaboada/python-samples-fastapi-restful#360]
## Description

Currently, the project uses manual Docker build/run commands and stores the SQLite database inside the container filesystem. This violates container immutability and doesn’t persist data between runs.

## Proposed Solution

Introduce Docker Compose to:

- Automate image building and container orchestration
- Mount a Docker-managed volume to persist the SQLite database across container restarts
- Copy a pre-seeded `players-sqlite3.db` from the image to the volume only on first run

## Suggested Implementation

`docker-compose.yml`
```yaml
services:
  api:
    image: python-samples-fastapi-restful
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - sqlite3-db:/sqlite3-db/
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_FILE_PATH=/sqlite3-db/players-sqlite3.db
    restart: unless-stopped

volumes:
  sqlite3-db:
```

`Dockerfile`
```yaml
# Copy entrypoint sctipt and SQLite database
COPY --chown=root:root --chmod=755      scripts/entrypoint.sh       ./entrypoint.sh
COPY --chown=root:root --chmod=755      sqlite3-db                  ./docker-compose

# Create non-root user and make volume mount point writable
RUN groupadd --system fastapi && \
    adduser --system --ingroup fastapi --disabled-password --gecos '' fastapi && \
    mkdir -p /sqlite3-db && \
    chown fastapi:fastapi /sqlite3-db
```

`scripts/entrypoint.sh`
```bash
#!/bin/bash
set -e

IMAGE_DATABASE_FILE_PATH="/app/docker-compose/players-sqlite3.db"
VOLUME_DATABASE_FILE_PATH="/sqlite3-db/players-sqlite3.db"

echo "✔ Starting container..."

if [ ! -f "$VOLUME_DATABASE_FILE_PATH" ]; then
    echo "⚠️ No existing database file found in volume."
    if [ -f "$IMAGE_DATABASE_FILE_PATH" ]; then
        echo "Copying database file to writable volume..."
        cp "$IMAGE_DATABASE_FILE_PATH" "$VOLUME_DATABASE_FILE_PATH"
        echo "✔ Database initialized at $VOLUME_DATBASE_FILE_PATH"
    else
        echo "⚠️ Database file missing at $IMAGE_DATABASE_FILE_PATH"
        exit 1
    fi
else
    echo "✔ Existing database file found. Skipping seed copy."
fi

echo "✔ Ready!"
echo "🚀 Launching app..."
exec "$@"
```

## Acceptance Criteria

- `docker compose up` builds and runs the container with FastAPI app on port 9000
- SQLite DB is copied to the volume only if not already present
- Data persists after `docker compose down` and is restored on next `up`
- `docker compose down -v` resets the DB, and re-seeds it on next run
- `README.md` is updated with Compose usage instructions
